apiVersion: autoscaling/v1
kind: HorizontalPodScaler
metadata:
  name: redis-master-hpa
  namespace: staging
spec:
  scaleTargetref:
    apiVersion: apps/v1
    kind: Deployment
    name: redis-master
  minRepicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 10
