apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: {{ template "guestbook.name" . }}
    tier: frontend
    chart: {{ template "guestbook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
     
  selector:
    app: {{ template "guestbook.name" . }}
    tier: frontend
    release: {{ .Release.Name }}
