apiVersion: v1
kind: Service
metadata:
  name: redis-{{ .Values.sredis.role }}
  labels:
    app: redis
    role: {{ .Values.sredis.role }}
    tier: backend
    chart: {{ template "guestbook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.sredis.service.type }}
  ports:
    - port: {{ .Values.sredis.service.port }}
      # targetPort: http
      # protocol: TCP
      # name: http
  selector:
    app: redis
    role: {{ .Values.sredis.role }}
    tier: backend
    release: {{ .Release.Name }}
